/* =====================================================================
   view/customers  ·  customers-1.0
   Customer master CRUD + dedicated import/export UI.
   ===================================================================== */

let cEdit=null,cDraft=null,cTab='general',cSearch='',cFilter='active';
function customerVisibleRows(){
 const q=customerString(cSearch).toLowerCase();
 return DB.customer.filter(c=>{
  if(cFilter==='active'&&c.status!=='active')return false;
  if(cFilter==='prospect'&&!c.isProspect)return false;
  if(cFilter==='hold'&&!c.onHold)return false;
  if(cFilter==='archived'&&c.status!=='archived')return false;
  if(q){const p=customerPrimaryContact(c),hay=[c.code,c.legalName,c.displayName,c.customerType,c.group,c.area,c.salesRep,c.taxNumber,p.name,p.phone,p.email].join(' ').toLowerCase();if(!hay.includes(q))return false;}
  return true;
 });
}
function customerSearchChange(el){cSearch=el.value;const pos=el.selectionStart;render();requestAnimationFrame(()=>{const e=document.getElementById('customerSearch');if(e){e.focus();try{e.setSelectionRange(pos,pos);}catch(x){}}});}
function viewCustomers(){
 const active=DB.customer.filter(c=>c.status==='active').length,prospects=DB.customer.filter(c=>c.isProspect).length,holds=DB.customer.filter(c=>c.onHold).length,arch=DB.customer.filter(c=>c.status==='archived').length;
 return `<div class="page-head"><div><h2>Клиенты</h2><p>Единый справочник клиентов для будущих Sales Orders. Контакты, адреса, кредитные условия и legacy-ID хранятся отдельно и не смешиваются с производственными данными.</p></div><span class="pill info">Customer Master · v1</span></div>
  <div class="kpi-grid">
   <div class="kpi"><div class="kpi-top"><div class="kpi-icon">${ico('users')}</div></div><div class="kpi-num">${active}</div><div class="kpi-label">активных клиентов</div></div>
   <div class="kpi"><div class="kpi-top"><div class="kpi-icon">${ico('sales')}</div></div><div class="kpi-num">${prospects}</div><div class="kpi-label">prospects</div></div>
   <div class="kpi"><div class="kpi-top"><div class="kpi-icon">${ico('alert')}</div></div><div class="kpi-num">${holds}</div><div class="kpi-label">на hold</div></div>
   <div class="kpi"><div class="kpi-top"><div class="kpi-icon">${ico('database')}</div></div><div class="kpi-num">${arch}</div><div class="kpi-label">в архиве</div></div>
  </div>
  ${cEdit!==null?customerForm():customerList()}`;
}
function customerList(){
 const rows=customerVisibleRows();
 return `<div class="card">
  <div class="customer-toolbar">
   <div class="customer-search"><input id="customerSearch" value="${esc(cSearch)}" placeholder="Поиск по коду, имени, контакту, телефону, email…" oninput="customerSearchChange(this)"></div>
   <div class="customer-actions"><button class="pri" onclick="customerNew()">+ Новый клиент</button><button onclick="exportCustomersCSV()">Экспорт CSV</button><button onclick="exportCustomersJSON()">Экспорт JSON</button><button onclick="document.getElementById('customerImportMerge').click()">Импорт / обновление</button><button class="dl" onclick="document.getElementById('customerImportReplace').click()">Импорт с заменой</button></div>
  </div>
  <input id="customerImportMerge" type="file" accept=".csv,.json,text/csv,application/json" hidden onchange="importCustomersFile(this,'merge')">
  <input id="customerImportReplace" type="file" accept=".csv,.json,text/csv,application/json" hidden onchange="importCustomersFile(this,'replace')">
  <div class="customer-filterbar">
   ${[['active','Активные'],['all','Все'],['prospect','Prospects'],['hold','On Hold'],['archived','Архив']].map(x=>`<button class="sm ${cFilter===x[0]?'customer-filter-on':''}" onclick="cFilter='${x[0]}';render()">${x[1]}</button>`).join('')}
   <span class="mut">Показано: ${rows.length} / ${DB.customer.length}</span>
  </div>
  <div class="customer-table-wrap"><table><thead><tr><th>Account</th><th>Клиент</th><th>Основной контакт</th><th>Условия</th><th>Кредит</th><th>Статус</th><th></th></tr></thead><tbody>${rows.map(customerRow).join('')||'<tr><td colspan="7" class="empty">клиенты не найдены</td></tr>'}</tbody></table></div>
  <div class="hint">CSV-импорт понимает как экспорт GLASS ERP, так и legacy-колонки Name / Account / Post Add / Del Add / Telephone / EMail / SalesRep / Credit Limit / DCLink и др.</div>
 </div>`;
}
function customerRow(c){
 const p=customerPrimaryContact(c),hold=c.onHold?'<span class="pill bad">On Hold</span>':'',prospect=c.isProspect?'<span class="pill info">Prospect</span>':'';
 const statusClass=c.status==='archived'?'warn':c.status==='inactive'?'info':'ok';
 return `<tr><td class="mono"><b>${raw(c.code||'—')}</b></td><td><b>${raw(c.displayName||c.legalName)}</b><div class="mut">${raw(c.legalName!==c.displayName?c.legalName:'')}</div></td>
  <td>${p.name?`<b>${raw(p.name)}</b><div class="mut">${raw(p.phone||p.mobile||'')} ${p.email?'· '+raw(p.email):''}</div>`:'<span class="mut">—</span>'}</td>
  <td>${raw(c.paymentTerms||'—')}<div class="mut">${esc(c.currency)} · ${raw(c.defaultDeliveryMethod||'—')}</div></td>
  <td>${c.creditLimit==null?'<span class="mut">—</span>':`<span class="mono">${esc(c.currency)} ${esc(c.creditLimit.toLocaleString('en-CA',{maximumFractionDigits:2}))}</span>`}<div>${hold}</div></td>
  <td><span class="pill ${statusClass}">${customerStatusLabel(c.status)}</span> ${prospect}</td>
  <td class="customer-row-actions"><button class="sm" onclick="customerEdit('${esc(c.id)}')">Открыть</button><button class="sm" onclick="customerDuplicate('${esc(c.id)}')">Дублировать</button><button class="sm" onclick="customerToggleArchive('${esc(c.id)}')">${c.status==='archived'?'Восстановить':'В архив'}</button><button class="sm dl" onclick="customerDelete('${esc(c.id)}')">×</button></td></tr>`;
}
function customerNew(){cEdit='new';cDraft=newCustomerDraft();cTab='general';render();}
function customerEdit(id){const c=DB.customer.find(x=>x.id===id);if(!c)return;cEdit=id;cDraft=JSON.parse(JSON.stringify(c));cTab='general';render();}
function customerDuplicate(id){const src=DB.customer.find(x=>x.id===id);if(!src)return;cEdit='new';cDraft=normalizeCustomer(JSON.parse(JSON.stringify(src)));cDraft.id=customerUid('CUS');cDraft.code='';cDraft.legalName+=(cDraft.legalName?' — копия':'');cDraft.displayName+=(cDraft.displayName?' — копия':'');cDraft.createdAt=new Date().toISOString();cDraft.updatedAt=cDraft.createdAt;cTab='general';render();}
function customerToggleArchive(id){const c=DB.customer.find(x=>x.id===id);if(!c)return;if(c.status==='archived'){c.status='active';c.archivedAt='';}else{c.status='archived';c.archivedAt=new Date().toISOString();}c.updatedAt=new Date().toISOString();touch();render();}
function customerDelete(id){const i=DB.customer.findIndex(x=>x.id===id);if(i<0)return;if(customerHasReferences(id)){alert('Клиент уже используется в заказах. Удаление запрещено — переведи клиента в архив.');return;}if(!confirm('Удалить клиента без возможности восстановления?'))return;DB.customer.splice(i,1);touch();render();}
function customerTabButton(id,label){return `<button class="${cTab===id?'on':''}" onclick="cTab='${id}';render()">${label}</button>`;}
function customerForm(){
 const c=cDraft;
 return `<div class="card customer-editor">
  <div class="section-title"><div><h3>${cEdit==='new'?'Новый клиент':raw(c.displayName||c.legalName||'Клиент')}</h3><div class="sub">Внутренний ID: <span class="mono" data-raw>${esc(c.id)}</span></div></div><div class="row customer-editor-actions"><button class="pri" onclick="saveCustomer()">Сохранить</button><button onclick="cEdit=null;cDraft=null;render()">Отмена</button></div></div>
  <div class="tabs customer-tabs">${customerTabButton('general','Основное')}${customerTabButton('contacts','Контакты')}${customerTabButton('addresses','Адреса')}${customerTabButton('credit','Кредит и условия')}${customerTabButton('accounting','Accounting')}${customerTabButton('legacy','Legacy IDs')}</div>
  ${cTab==='general'?customerGeneralForm():cTab==='contacts'?customerContactsForm():cTab==='addresses'?customerAddressesForm():cTab==='credit'?customerCreditForm():cTab==='accounting'?customerAccountingForm():customerLegacyForm()}
  <div class="err" id="e_customer"></div>
 </div>`;
}
function customerGeneralForm(){const c=cDraft;return `<div class="form"><h3>Основная информация</h3><div class="grid customer-grid-4">
 <div><label>Account / Customer Code</label><input value="${esc(c.code)}" placeholder="авто: C-00001" oninput="cDraft.code=this.value"></div>
 <div><label>Legal Name *</label><input value="${esc(c.legalName)}" oninput="cDraft.legalName=this.value;if(!cDraft.displayName)cDraft.displayName=this.value"></div>
 <div><label>Display Name</label><input value="${esc(c.displayName)}" oninput="cDraft.displayName=this.value"></div>
 <div><label>Статус</label><select onchange="cDraft.status=this.value"><option value="active" ${c.status==='active'?'selected':''}>Активный</option><option value="inactive" ${c.status==='inactive'?'selected':''}>Неактивный</option><option value="archived" ${c.status==='archived'?'selected':''}>Архив</option></select></div>
 <div><label>Customer Type</label><input value="${esc(c.customerType)}" oninput="cDraft.customerType=this.value"></div><div><label>Group</label><input value="${esc(c.group)}" oninput="cDraft.group=this.value"></div><div><label>Area / Territory</label><input value="${esc(c.area)}" oninput="cDraft.area=this.value"></div><div><label>Sales Rep</label><input value="${esc(c.salesRep)}" oninput="cDraft.salesRep=this.value"></div>
 <div><label>Account Open Date</label><input type="date" value="${esc(c.accountOpenedAt)}" onchange="cDraft.accountOpenedAt=this.value"></div><div><label>TAX Number</label><input value="${esc(c.taxNumber)}" oninput="cDraft.taxNumber=this.value"></div><div><label>Registration</label><input value="${esc(c.registrationNumber)}" oninput="cDraft.registrationNumber=this.value"></div><div class="customer-checks"><label class="chk"><input type="checkbox" ${c.isProspect?'checked':''} onchange="cDraft.isProspect=this.checked"> Prospect</label><label class="chk"><input type="checkbox" ${c.poRequired?'checked':''} onchange="cDraft.poRequired=this.checked"> PO обязателен</label></div>
 </div><div class="grid" style="margin-top:12px"><div><label>Notes</label><textarea rows="3" oninput="cDraft.notes=this.value">${esc(c.notes)}</textarea></div><div><label>Internal Notes</label><textarea rows="3" oninput="cDraft.internalNotes=this.value">${esc(c.internalNotes)}</textarea></div></div></div>`;}
function customerContactsForm(){const c=cDraft;return `<div class="section-title"><div><h3>Контакты</h3><div class="sub">Несколько людей на одного клиента: purchasing, accounting, receiving, project manager и др.</div></div><button class="pri" onclick="customerAddContact()">+ Контакт</button></div>${c.contacts.map((x,i)=>`<div class="form customer-subrecord"><div class="customer-subrecord-head"><b>Контакт ${i+1}</b><button class="sm dl" onclick="customerRemoveContact(${i})">Удалить</button></div><div class="grid customer-grid-4"><div><label>Имя</label><input value="${esc(x.name)}" oninput="cDraft.contacts[${i}].name=this.value"></div><div><label>Роль / должность</label><input value="${esc(x.role)}" oninput="cDraft.contacts[${i}].role=this.value"></div><div><label>Phone</label><input value="${esc(x.phone)}" oninput="cDraft.contacts[${i}].phone=this.value"></div><div><label>Phone 2</label><input value="${esc(x.phone2)}" oninput="cDraft.contacts[${i}].phone2=this.value"></div><div><label>Mobile</label><input value="${esc(x.mobile)}" oninput="cDraft.contacts[${i}].mobile=this.value"></div><div><label>Fax</label><input value="${esc(x.fax)}" oninput="cDraft.contacts[${i}].fax=this.value"></div><div><label>Email</label><input type="email" value="${esc(x.email)}" oninput="cDraft.contacts[${i}].email=this.value"></div><div class="customer-checks"><label class="chk"><input type="checkbox" ${x.isPrimary?'checked':''} onchange="customerContactFlag(${i},'isPrimary',this.checked)"> Основной</label><label class="chk"><input type="checkbox" ${x.isInvoice?'checked':''} onchange="customerContactFlag(${i},'isInvoice',this.checked)"> Invoice</label><label class="chk"><input type="checkbox" ${x.isShipping?'checked':''} onchange="customerContactFlag(${i},'isShipping',this.checked)"> Shipping</label></div></div></div>`).join('')||'<div class="empty">Контактов пока нет</div>'}`;}
function customerAddContact(){cDraft.contacts.push(normalizeCustomerContact({}));render();}function customerRemoveContact(i){cDraft.contacts.splice(i,1);render();}function customerContactFlag(i,k,v){if(v)cDraft.contacts.forEach((x,n)=>{if(n!==i)x[k]=false;});cDraft.contacts[i][k]=v;render();}
function customerAddressesForm(){const c=cDraft;return `<div class="section-title"><div><h3>Адреса</h3><div class="sub">Billing и несколько delivery/job-site адресов могут существовать одновременно.</div></div><button class="pri" onclick="customerAddAddress()">+ Адрес</button></div>${c.addresses.map((x,i)=>`<div class="form customer-subrecord"><div class="customer-subrecord-head"><b>Адрес ${i+1}</b><button class="sm dl" onclick="customerRemoveAddress(${i})">Удалить</button></div><div class="grid customer-grid-4"><div><label>Тип</label><select onchange="cDraft.addresses[${i}].type=this.value"><option value="billing" ${x.type==='billing'?'selected':''}>Billing</option><option value="delivery" ${x.type==='delivery'?'selected':''}>Delivery</option><option value="other" ${x.type==='other'?'selected':''}>Other</option></select></div><div><label>Название</label><input value="${esc(x.label)}" placeholder="Main warehouse / Job Site" oninput="cDraft.addresses[${i}].label=this.value"></div><div><label>Addressee</label><input value="${esc(x.addressee)}" oninput="cDraft.addresses[${i}].addressee=this.value"></div><div class="customer-checks"><label class="chk"><input type="checkbox" ${x.isDefault?'checked':''} onchange="customerAddressDefault(${i},this.checked)"> По умолчанию</label></div><div><label>Address 1</label><input value="${esc(x.address1)}" oninput="cDraft.addresses[${i}].address1=this.value"></div><div><label>Address 2</label><input value="${esc(x.address2)}" oninput="cDraft.addresses[${i}].address2=this.value"></div><div><label>Address 3</label><input value="${esc(x.address3)}" oninput="cDraft.addresses[${i}].address3=this.value"></div><div><label>City</label><input value="${esc(x.city)}" oninput="cDraft.addresses[${i}].city=this.value"></div><div><label>Province / State</label><input value="${esc(x.province)}" oninput="cDraft.addresses[${i}].province=this.value"></div><div><label>Postal Code</label><input value="${esc(x.postalCode)}" oninput="cDraft.addresses[${i}].postalCode=this.value"></div><div><label>Country</label><input value="${esc(x.country)}" oninput="cDraft.addresses[${i}].country=this.value"></div></div></div>`).join('')||'<div class="empty">Адресов пока нет</div>'}`;}
function customerAddAddress(){cDraft.addresses.push(normalizeCustomerAddress({type:'delivery',country:'Canada'}));render();}function customerRemoveAddress(i){cDraft.addresses.splice(i,1);render();}function customerAddressDefault(i,v){if(v)cDraft.addresses.forEach((x,n)=>{if(n!==i&&x.type===cDraft.addresses[i].type)x.isDefault=false;});cDraft.addresses[i].isDefault=v;render();}
function customerCreditForm(){const c=cDraft;return `<div class="form"><h3>Кредит и коммерческие условия</h3><div class="grid customer-grid-4"><div><label>Payment Terms</label><input value="${esc(c.paymentTerms)}" placeholder="45 Days Net" oninput="cDraft.paymentTerms=this.value"></div><div><label>Currency</label><select onchange="cDraft.currency=this.value">${CUSTOMER_CURRENCIES.map(x=>`<option ${c.currency===x?'selected':''}>${x}</option>`).join('')}</select></div><div><label>Credit Limit</label><input type="number" step="0.01" min="0" value="${c.creditLimit==null?'':esc(c.creditLimit)}" oninput="cDraft.creditLimit=this.value"></div><div><label>Credit Application Date</label><input type="date" value="${esc(c.creditApplicationDate)}" onchange="cDraft.creditApplicationDate=this.value"></div><div class="customer-checks"><label class="chk"><input type="checkbox" ${c.onHold?'checked':''} onchange="cDraft.onHold=this.checked;render()"> On Hold</label><label class="chk"><input type="checkbox" ${c.checkTerms?'checked':''} onchange="cDraft.checkTerms=this.checked"> Check Terms</label></div><div><label>Hold Reason</label><input value="${esc(c.holdReason)}" ${c.onHold?'':'disabled'} oninput="cDraft.holdReason=this.value"></div><div><label>Delivery Method</label><input value="${esc(c.defaultDeliveryMethod)}" placeholder="Pickup / Company Truck" oninput="cDraft.defaultDeliveryMethod=this.value"></div><div><label>Deliver To</label><input value="${esc(c.deliverTo)}" oninput="cDraft.deliverTo=this.value"></div><div><label>Fuel Levy</label><select onchange="cDraft.fuelLevyMode=this.value;render()"><option value="default" ${c.fuelLevyMode==='default'?'selected':''}>По умолчанию</option><option value="custom" ${c.fuelLevyMode==='custom'?'selected':''}>Индивидуальная ставка</option><option value="exempt" ${c.fuelLevyMode==='exempt'?'selected':''}>Без топливного сбора</option></select></div><div><label>Fuel Levy Rate</label><input type="number" step="0.0001" min="0" value="${c.fuelLevyRate==null?'':esc(c.fuelLevyRate)}" ${c.fuelLevyMode==='custom'?'':'disabled'} oninput="cDraft.fuelLevyRate=this.value"></div></div></div>`;}
function customerAccountingForm(){const c=cDraft;return `<div class="form"><h3>Accounting и statements</h3><div class="grid customer-grid-4"><div><label>Statement Delivery</label><select onchange="cDraft.statementDelivery=this.value"><option value="email" ${c.statementDelivery==='email'?'selected':''}>Email</option><option value="print" ${c.statementDelivery==='print'?'selected':''}>Печать</option><option value="both" ${c.statementDelivery==='both'?'selected':''}>Email + печать</option><option value="none" ${c.statementDelivery==='none'?'selected':''}>Не отправлять</option></select></div><div><label>Statement Email</label><input type="email" value="${esc(c.statementEmail)}" oninput="cDraft.statementEmail=this.value"></div><div><label>Invoice Email</label><input type="email" value="${esc(c.invoiceEmail)}" oninput="cDraft.invoiceEmail=this.value"></div><div><label>TAX Exempt</label><label class="chk"><input type="checkbox" ${c.taxExempt?'checked':''} onchange="cDraft.taxExempt=this.checked;render()"> Tax Exempt</label></div><div><label>Tax Exemption Number</label><input value="${esc(c.taxExemptionNumber)}" ${c.taxExempt?'':'disabled'} oninput="cDraft.taxExemptionNumber=this.value"></div></div></div>`;}
function customerLegacyForm(){const l=cDraft.legacyRefs||normalizeLegacyRefs({});cDraft.legacyRefs=l;return `<div class="note">Legacy IDs сохраняются для миграции и сверки со старой системой. Они не являются бизнес-ключами новой ERP.</div><div class="form"><h3>Legacy / migration references</h3><div class="grid customer-grid-4"><div><label>Source System</label><input value="${esc(l.sourceSystem)}" oninput="cDraft.legacyRefs.sourceSystem=this.value"></div>${[['dcLink','DCLink'],['flid','FLID'],['iClassID','iClassID'],['repID','RepID'],['iAreasID','iAreasID'],['uiARDeliveryMethod','uiARDeliveryMethod'],['uiARCATID','uiARCATID'],['accountStatusID','AccountStatusID'],['iwg','I.W.G']].map(x=>`<div><label>${x[1]}</label><input value="${esc(l[x[0]])}" oninput="cDraft.legacyRefs.${x[0]}=this.value"></div>`).join('')}</div></div>`;}
function saveCustomer(){
 const e=document.getElementById('e_customer');e.style.display='none';
 cDraft=normalizeCustomer(cDraft);cDraft.legalName=customerString(cDraft.legalName);cDraft.displayName=customerString(cDraft.displayName)||cDraft.legalName;
 if(!cDraft.legalName)return fail(e,'Укажи Legal Name');
 if(!cDraft.code)cDraft.code=nextCustomerCode();
 if(DB.customer.some(c=>c.id!==cDraft.id&&String(c.code).toUpperCase()===String(cDraft.code).toUpperCase()))return fail(e,'Customer Code уже используется');
 if(cDraft.onHold&&!cDraft.holdReason)cDraft.holdReason='Management hold';
 cDraft.updatedAt=new Date().toISOString();if(!cDraft.createdAt)cDraft.createdAt=cDraft.updatedAt;if(cDraft.status==='archived'&&!cDraft.archivedAt)cDraft.archivedAt=cDraft.updatedAt;if(cDraft.status!=='archived')cDraft.archivedAt='';
 if(cEdit==='new')DB.customer.push(cDraft);else{const i=DB.customer.findIndex(c=>c.id===cEdit);if(i>=0)DB.customer[i]=cDraft;else DB.customer.push(cDraft);}
 normalizeCustomers();cEdit=null;cDraft=null;touch();render();
}
